"""CPU tests for experiments/diag_fit.py on synthetic data. Run: python tests/test_diag_fit.py"""
from __future__ import annotations

import csv
import json
import sys
import tempfile
from pathlib import Path

import numpy as np

_REPO = Path(__file__).resolve().parents[1]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from experiments.diag_fit import (alpha_pred, annotate, concat, fit_alpha, fit_gamma, fit_margins, fit_mechform,  # noqa: E402
                                  fit_mechform_cell, fit_sharelaw, headscan, law, load_runs, main, read_table, summary_table)

NS = (8, 16, 32, 64, 128)


# ------------------------------------------------------------------------------ synthetic writers
def _write_csv(path, rows, cols):
    with open(path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols)
        w.writeheader()
        w.writerows(rows)


def flip_tables(N, alpha=0.72, n_pairs=40, seed=0, qtype="steps_in_room", arm="plain", layers=(20,), golds=(1, 2, 3),
                gamma=None, gamma_C=2.0, amp=20.0, sigma=0.2, qid_prefix="q"):
    """pairs/controls/logits rows for one N; median dnorm = amp * N^-alpha (* (gold+C)^-gamma if gamma) with
    lognormal noise. Each pair = one evid flip; controls = replay (0) / ctrl / perm rows."""
    rng = np.random.RandomState(seed + N)
    pairs, controls, logits = [], [], []
    for i in range(n_pairs):
        gold = golds[i % len(golds)]
        qid = f"{qid_prefix}_{qtype}_N{N}_{i:04d}"
        flip_t = int(rng.randint(0, N))
        for layer in layers:
            med = amp * N ** (-alpha) * ((gold + gamma_C) ** (-gamma) if gamma is not None else 1.0)
            d = med * np.exp(sigma * rng.randn())
            pairs.append(dict(qid=qid, qtype=qtype, n_frames=N, gold=gold, flip_t=flip_t, flip_kind="evid", arm=arm, layer=layer,
                              locus="final", dnorm=f"{d:.6f}", base_norm="100"))
            if i < 10:
                for kind, v in (("replay", 0.0), ("ctrl", 0.05 * np.exp(0.1 * rng.randn())), ("perm", 0.1)):
                    controls.append(dict(qid=qid, qtype=qtype, n_frames=N, kind=kind, arm=arm, layer=layer, locus="final",
                                         dnorm=f"{v:.6f}", base_norm="100"))
        mb = 2.0 - 0.02 * N + 0.3 * rng.randn()
        pred_base = gold if mb > 0 else gold + 1
        logits.append(dict(qid=qid, qtype=qtype, n_frames=N, gold=gold, arm=arm, flip_kind="evid", margin_base=f"{mb:.4f}",
                           margin_flip=f"{mb - 1.0:.4f}", pred_base=pred_base, pred_flip=pred_base + 1, dlogit="1.0"))
        if i < 10:
            logits.append(dict(qid=qid, qtype=qtype, n_frames=N, gold=gold, arm=arm, flip_kind="ctrl", margin_base=f"{mb:.4f}",
                               margin_flip=f"{mb + 0.05:.4f}", pred_base=pred_base, pred_flip=pred_base, dlogit="0.05"))
    return pairs, controls, logits


PAIR_COLS = "qid,qtype,n_frames,gold,flip_t,flip_kind,arm,layer,locus,dnorm,base_norm".split(",")
CTRL_COLS = "qid,qtype,n_frames,kind,arm,layer,locus,dnorm,base_norm".split(",")
LOGIT_COLS = "qid,qtype,n_frames,gold,arm,flip_kind,margin_base,margin_flip,pred_base,pred_flip,dlogit".split(",")
MASS_COLS = "qid,qtype,N,k,layer,head,evid_mass,nonevid_mass,other_mass".split(",")
BLOCK_COLS = "qid,qtype,N,k,layer,head,block,is_evid,mass".split(",")


def photo_tables(N, ks=(2, 4, 8), s=0.3, C=8.0, noise=0.01, n_samples=20, n_heads=4, layer=20, seed=0, qtype="steps_in_room"):
    """mass/block_mass rows generated by the share law (+ gaussian noise on the head-level evid mass)."""
    rng = np.random.RandomState(seed + N)
    mass, blocks, auc = [], [], {}
    for k in ks:
        m = float(law((np.array([N], float), np.array([k], float)), s, C)[0])
        for i in range(n_samples):
            qid = f"{qtype}_N{N}_K{k}_{i:04d}"
            evid_blocks = set(rng.choice(N, k, replace=False).tolist())
            for h in range(n_heads):
                e = min(max(m + noise * rng.randn(), 1e-4), 0.999)
                ne = (1 - e) * 0.8
                mass.append(dict(qid=qid, qtype=qtype, N=N, k=k, layer=layer, head=h, evid_mass=f"{e:.6f}",
                                 nonevid_mass=f"{ne:.6f}", other_mass=f"{1 - e - ne:.6f}"))
                for b in range(N):
                    is_e = int(b in evid_blocks)
                    mb = e / k if is_e else ne / max(N - k, 1)
                    blocks.append(dict(qid=qid, qtype=qtype, N=N, k=k, layer=layer, head=h, block=b, is_evid=is_e, mass=f"{mb:.6f}"))
    for h in range(n_heads):
        auc[f"L{layer}_h{h}"] = 0.99 if h == 0 else 0.7 + 0.05 * h
    auc["L24_h20"] = 0.999
    return mass, blocks, auc


def write_flip_run(d, N, **kw):
    d = Path(d)
    d.mkdir(parents=True, exist_ok=True)
    pairs, controls, logits = flip_tables(N, **kw)
    _write_csv(d / "pairs.csv", pairs, PAIR_COLS)
    _write_csv(d / "controls.csv", controls, CTRL_COLS)
    _write_csv(d / "logits.csv", logits, LOGIT_COLS)
    (d / "config.json").write_text(json.dumps({"config": f"seq_len_{N}", "split": "test", "qtypes": [kw.get("qtype", "steps_in_room")],
                                               "arms": [kw.get("arm", "plain")], "attn_sharpen": 0, "sharpen_from_layer": 12,
                                               "attn_logn_sref": 0, "adapter": None}))


def write_photo_run(d, N, arm="qfirst", tau=0, **kw):
    d = Path(d)
    d.mkdir(parents=True, exist_ok=True)
    mass, blocks, auc = photo_tables(N, **kw)
    _write_csv(d / "mass.csv", mass, MASS_COLS)
    _write_csv(d / "block_mass.csv", blocks, BLOCK_COLS)
    (d / "auc.json").write_text(json.dumps(auc))
    (d / "config.json").write_text(json.dumps({"config": f"seq_len_{N}", "arm": arm, "qtypes": [kw.get("qtype", "steps_in_room")],
                                               "attn_sharpen": tau, "sharpen_from_layer": 12, "attn_logn_sref": 0, "adapter": None}))


def _tables(rows, cols, N, cfg=None):
    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / "t.csv"
        _write_csv(p, rows, cols)
        return annotate(read_table(p), cfg or {}, f"run_N{N}")


# --------------------------------------------------------------------------------------- tests
def test_alpha_recovers_exponent():
    P, Cc = [], []
    for N in NS:
        pairs, controls, _ = flip_tables(N, alpha=0.72, n_pairs=60)
        P.append(_tables(pairs, PAIR_COLS, N))
        Cc.append(_tables(controls, CTRL_COLS, N))
    res = fit_alpha(concat(P), concat(Cc), n_boot=500)
    assert len(res["cells"]) == 1, res["cells"]
    c = res["cells"][0]
    assert (c["qtype"], c["arm"], c["cond"], c["model"], c["layer"], c["locus"]) == ("steps_in_room", "plain", "base", "frozen", 20, "final")
    assert abs(c["alpha"] - 0.72) < 0.03, c["alpha"]
    assert c["ci"][0] < 0.72 < c["ci"][1] and c["r2"] > 0.95, (c["ci"], c["r2"])
    assert c["N"] == list(NS) and c["n"] == [60] * 5
    assert c["floors"]["replay"]["max"] == 0.0 and 0.03 < c["floors"]["ctrl"]["median"] < 0.07 and c["floors"]["perm"]["per_N"][8] == 0.1
    assert set(c["by_gold"]) == {"1", "2", "3"} and all(abs(f["alpha"] - 0.72) < 0.1 for f in c["by_gold"].values())
    assert set(c["by_position"]) == {"first", "middle", "last"}
    assert "pooled alpha 0.7" in c["pooled_vs_stratified"]


def test_alpha_legacy_columns_and_missing_N():
    rows = []
    rng = np.random.RandomState(1)
    for N in (8, 32, 128):                        # legacy schema: sample_id, no qtype, no flip_kind variety
        for i in range(30):
            rows.append(dict(sample_id=f"s{N}_{i}", n_frames=N, gold=0, flip_t=1, flip_kind="evid", arm="plain", layer=20, locus="final",
                             dnorm=f"{5 * N ** -0.5 * np.exp(0.1 * rng.randn()):.5f}", base_norm=1))
    t = _tables(rows, list(rows[0]), 0, cfg={"data_root": "x/seq_len_8/y", "attn_logn_sref": 0, "peft_adapter": "checkpoints/ada"})
    c = fit_alpha(t, None, n_boot=200)["cells"][0]
    assert c["qtype"] == "steps_in_room" and c["model"] == "ada" and c["cond"] == "base" and c["N"] == [8, 32, 128]
    assert abs(c["alpha"] - 0.5) < 0.05 and c["floors"] == {}


def test_sharelaw_recovers_s_C_and_alpha_pred():
    exact = alpha_pred(0.3, 8.0, 4)
    assert abs(exact - 0.716) < 0.005, exact                     # the record's number (memory share-law-predicts-alpha)
    assert abs(alpha_pred(0.3, 8.0, 4, B=8) - 0.154) < 0.005 and alpha_pred(0.3, 8.0, 4, B=np.inf) == 0.0
    for noise, tol_s, tol_C, tol_a in ((0.0, 1e-3, 0.05, 0.01), (0.01, 0.05, 1.5, 0.05)):
        M, Bk = [], []
        for N in (8, 16, 32, 64):
            mass, blocks, _ = photo_tables(N, noise=noise, n_samples=12, n_heads=3)
            M.append(_tables(mass, MASS_COLS, N, {"arm": "qfirst"}))
            Bk.append(_tables(blocks, BLOCK_COLS, N, {"arm": "qfirst"}))
        res = fit_sharelaw(concat(M), concat(Bk), n_boot=50)
        f = res["fits"][0]
        assert f["form"] == "ungated" and f["best_form"] == "ungated" and f["layer"] == 20 and f["arm"] == "qfirst"
        assert abs(f["s"] - 0.3) < tol_s and abs(f["C"] - 8.0) < tol_C, (noise, f["s"], f["C"])
        assert f["r2"] > 0.99 and f["ci_s"][0] <= f["s"] <= f["ci_s"][1]
        assert abs(f["alpha_pred"]["4"] - exact) < tol_a, f["alpha_pred"]
        assert len(f["cells"]) == 12 and all(c["n"] == 12 for c in f["cells"])
        pf = f["perframe"]
        assert pf["N"][:3] == [8, 8, 8] and pf["k"][:3] == [2, 4, 8] and not np.isfinite(pf["ratio"][2])   # N=8,k=8: no non-evidence frames
        e64 = float(law((np.array([64.0]), np.array([8.0])), 0.3, 8.0)[0])                            # generator: e/k vs 0.8(1-e)/(N-k)
        assert abs(pf["ratio"][-1] / ((e64 / 8) / (0.8 * (1 - e64) / 56)) - 1) < 0.02 + 10 * noise, pf["ratio"][-1]
        assert pf["evid_slope"] < 0 and pf["nonevid_slope"] < pf["evid_slope"] and abs(pf["conc"][0] - 1.0) < 1e-6
        assert "2" in pf["slopes_by_k"]
    gated = {(N, k): np.full(5, law((np.array([N], float), np.array([k], float)), 0.26, 46.0, np.inf)[0]) for N in NS for k in (2, 4, 8)}
    from experiments.diag_fit import fit_law_boot
    g = fit_law_boot(gated, "gated", n_boot=5)
    assert abs(g["C_eff"] / (46 * np.exp(-0.26)) - 1) < 1e-3 and g["r2"] > 0.999, g      # gated form: only C e^-s identifiable


def test_gamma_recovers():
    rows = []
    for k in (1, 2, 4, 8, 16, 32):
        p, _, _ = flip_tables(64, alpha=0.0, n_pairs=40, golds=(k,), gamma=1.19, gamma_C=2.0, amp=50.0, sigma=0.15, seed=k)
        rows += p
    res = fit_gamma(_tables(rows, PAIR_COLS, 64), n_boot=300)
    assert len(res["cells"]) == 1
    c = res["cells"][0]
    assert c["N"] == 64 and c["k"] == [1, 2, 4, 8, 16, 32]
    assert abs(c["gamma"] - 1.19) < 0.05 and c["C"] == 2.0 and c["r2"] > 0.99, (c["gamma"], c["C"], c["r2"])
    assert c["ci"][0] < 1.19 < c["ci"][1] and "2.0" in c["grid"]


def test_mechform_recovers_G():
    Ns = np.array(NS, float)
    dm = law((Ns, np.full(5, 5.0)), 0.3, 8.0) - law((Ns, np.full(5, 4.0)), 0.3, 8.0)
    G = 37.0
    rng = np.random.RandomState(0)
    y = G * dm * np.exp(0.02 * rng.randn(5))
    r = fit_mechform_cell(Ns, y, 0.3, 8.0, k=4)
    assert abs(r["fixed"]["G"] / G - 1) < 0.05 and r["fixed"]["r2"] > 0.98, r["fixed"]
    assert r["free"] is not None and r["free"]["r2"] >= r["fixed"]["r2"] - 1e-9 and abs(r["free"]["dr2"]) < 0.01   # degenerate at 2% noise
    r0 = fit_mechform_cell(Ns, G * dm, 0.3, 8.0, k=4)                                  # zero noise: exact recovery
    assert abs(r0["fixed"]["G"] - G) < 1e-6 and abs(r0["free"]["G"] - G) < 1e-4 and abs(r0["free"]["s"] - 0.3) < 1e-4 and abs(r0["free"]["C"] - 8) < 1e-3
    alpha = {"cells": [{"qtype": "steps_in_room", "arm": a, "cond": "base", "model": "frozen", "layer": 20, "locus": "final",
                        "N": list(NS), "median": list(g * dm), "alpha": 0.72, "r2": 0.99} for a, g in (("plain", 10.0), ("gated", 30.0))]}
    share = {"fits": [{"qtype": "steps_in_room", "arm": "plain", "cond": "base", "model": "frozen", "layer": 20, "s": 0.3, "C": 8.0}]}
    res = fit_mechform(alpha, share, k=4)
    assert [c["arm"] for c in res["cells"]] == ["plain", "gated"] and abs(res["cells"][0]["fixed"]["G"] - 10) < 1e-6
    assert res["cells"][1]["sharelaw_match"] == {"qtype": "steps_in_room", "layer": 20} and len(res["which_moves"]) == 1
    assert res["which_moves"][0].startswith("steps_in_room base L20 final: plain/frozen -> gated/frozen: G_fixed x3.00")
    assert fit_mechform(alpha, None, k=4)["cells"] == [] and len(fit_mechform(alpha, None, k=4, s=0.3, C=8.0)["cells"]) == 2


def test_margins_and_headscan():
    L = [_tables(flip_tables(N, n_pairs=30)[2], LOGIT_COLS, N) for N in NS]
    res = fit_margins(concat(L))
    c = res["cells"][0]
    assert c["N"] == list(NS) and c["n"] == [30] * 5 and all(v == 1.0 for v in c["flip_changes_answer"])
    assert all(abs(f - 0.05) < 1e-6 for f in c["noise_floor"]) and c["n_cross_zero"] == 128 and 0 <= c["accuracy"][0] <= 1
    runs = [{"qtype": "q", "arm": "qfirst", "cond": "base", "model": "frozen", "N": N,
             "auc": {"L20_h0": 0.99, "L20_h1": 0.5 + N / 1000, "L24_h20": 0.999}} for N in (8, 16)]
    h = headscan(runs, "L24_h20")["groups"][0]
    assert h["N"] == [8, 16] and h["named"]["auc"] == {"8": 0.999, "16": 0.999} and h["population"]["8"]["count"] == 2
    assert h["best_per_layer"]["8"]["20"] == ["L20_h0", 0.99] and h["auc"]["L20_h1"]["16"] == 0.516


def test_cli_end_to_end():
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        for N in (8, 16, 32, 64):
            write_flip_run(td / "d1" / f"plain_N{N}", N, n_pairs=20)
            write_flip_run(td / "d1" / f"fenced_N{N}", N, n_pairs=20, arm="fenced", alpha=0.0, amp=5.0)
            write_photo_run(td / "d2" / f"qfirst_N{N}", N, n_samples=6, n_heads=2)
        write_photo_run(td / "d2" / "qfirst_N32_tau2", 32, tau=2.0, s=0.8, n_samples=6, n_heads=2)
        for k in (1, 2, 4, 8):
            write_flip_run(td / "s11" / f"gated_N64_k{k}", 64, n_pairs=15, arm="gated", golds=(k,), gamma=1.19, alpha=0.0, amp=50.0)
        out = td / "fits"
        assert main(["alpha", "--runs", str(td / "d1" / "*"), "--out", str(out / "alpha.json"), "--n-boot", "100"]) == 0
        assert main(["margins", "--runs", str(td / "d1" / "*"), "--out", str(out / "margins.json")]) == 0
        assert main(["sharelaw", "--runs", str(td / "d2" / "*"), "--out", str(out / "sharelaw.json"), "--n-boot", "20"]) == 0
        assert main(["headscan", "--runs", str(td / "d2" / "*"), "--out", str(out / "headscan.json")]) == 0
        assert main(["gamma", "--runs", str(td / "s11" / "*"), "--out", str(out / "gamma.json"), "--n-boot", "100"]) == 0
        assert main(["mechform", "--alpha", str(out / "alpha.json"), "--sharelaw", str(out / "sharelaw.json"), "--out", str(out / "mechform.json")]) == 0
        assert main(["summary", "--alpha", str(out / "alpha.json"), "--margins", str(out / "margins.json")]) == 0
        for name in ("alpha", "margins", "sharelaw", "headscan", "gamma", "mechform"):
            assert (out / f"{name}.json").exists() and (out / f"{name}.csv").exists(), name
        al = json.loads((out / "alpha.json").read_text())
        arms = {c["arm"]: c["alpha"] for c in al["cells"]}
        assert abs(arms["plain"] - 0.72) < 0.1 and abs(arms["fenced"]) < 0.1, arms
        sh = json.loads((out / "sharelaw.json").read_text())
        assert {f["cond"] for f in sh["fits"]} == {"base", "tau2L12"} and all(f["s"] is not None for f in sh["fits"])
        hs = json.loads((out / "headscan.json").read_text())
        assert [g["cond"] for g in hs["groups"]] == ["base", "tau2L12"] and hs["groups"][0]["N"] == [8, 16, 32, 64]
        from experiments.diag_fit import cond_of
        assert cond_of({"cond": "tau3L12"}) == "tau3L12" and cond_of({"attn_sharpen": 1.0}) == "base" and cond_of({"attn_logn_sref": 3398}) == "logn3398"
        ga = json.loads((out / "gamma.json").read_text())
        assert len(ga["cells"]) == 1 and abs(ga["cells"][0]["gamma"] - 1.19) < 0.15
        mf = json.loads((out / "mechform.json").read_text())
        assert [c["arm"] for c in mf["cells"]] == ["plain", "fenced"] and mf["cells"][0]["fixed"]["G"] > 0
        assert "| plain |" in summary_table(al) and load_runs([str(td / "nowhere")], "pairs") is None


if __name__ == "__main__":
    for name, fn in sorted(globals().items()):
        if name.startswith("test_") and callable(fn):
            print(name); fn()
    print("ALL OK")
