"""Held symbolic law for the predeclared factor fresh-validation panels.

No model inputs are generated by importing this module. Sampling and substantive
checks belong in a separately released Slurm CPU stager, after native trainability.
"""
from collections import Counter, defaultdict
import copy
import random

from scripts import stage_native_identity_join as ancestor

SEED = 91726341
LENGTHS = (16, 32, 64)
PEOPLE = tuple(ancestor.CHARS)
ROOMS = tuple(ancestor.PARK_ROOMS)
HELD_PAIRS = (('Kitchen', 'Bedroom'), ('Office', 'Bathroom'), ('Park', 'Garden'))
# The protocol names unordered room pairs. Preserve the original template's
# canonical room order, as in all earlier identity-join questions.
HELD_PAIRS = tuple(tuple(sorted(pair, key=ROOMS.index)) for pair in HELD_PAIRS)
need = ancestor.need
oid = ancestor.oid


def scene_content(row):
    return dict(question=row['question'], states=row['states'])


def family_identity(rows):
    """Concrete same-length triple, independent of labels, paths, seed or order."""
    need(len(rows) == 3 and len({len(r['states']) for r in rows}) == 1,
         'A concrete family requires three same-length scenes')
    contents = [scene_content(row) for row in rows]
    need(len({oid(value) for value in contents}) == 3, 'Duplicate family scene')
    return oid(sorted(contents, key=oid))


def panels(training_samples):
    need(len(training_samples) == 108, 'Exact original training subset required')
    trios = sorted({tuple(row['trio']) for row in training_samples},
                   key=lambda trio: tuple(PEOPLE.index(p) for p in trio))
    pairs = sorted({tuple(row['room_pair']) for row in training_samples},
                   key=lambda pair: tuple(ROOMS.index(room) for room in pair))
    need(trios == [tuple(PEOPLE[i:i+3]) for i in (0, 3, 6)] and len(pairs) == 6,
         'Original three trios and six seen questions required')
    new_trios = [tuple(trios[j][i] for j in range(3)) for i in range(3)]
    need(not set(new_trios) & set(trios) and not set(HELD_PAIRS) & set(pairs),
         'New composition or question panel overlaps the fitted support')
    orientation = defaultdict(set)
    for row in training_samples:
        orientation[(tuple(row['trio']), tuple(row['room_pair']))].add(row['orientation'])
    need(len(orientation) == 18 and all(len(v) == 1 for v in orientation.values()),
         'Training orientation must be unique in each original cell')
    result = []
    for panel, chosen_trios, chosen_pairs in (('A', trios, pairs), ('B', new_trios, pairs),
                                            ('C', new_trios, list(HELD_PAIRS))):
        for ti, trio in enumerate(chosen_trios):
            for pi, pair in enumerate(chosen_pairs):
                for direction in (0, 1):
                    original = next(iter(orientation[(trio, pair)])) if panel == 'A' else None
                    result.append(dict(panel=panel, trio=list(trio), room_pair=list(pair),
                        orientation=direction, original_training_orientation=original,
                        matches_training_orientation=None if original is None else direction == original,
                        label=f'factor_fresh/{panel}/{ti}/{pi}/{direction}'))
    need(Counter(r['panel'] for r in result) == {'A': 36, 'B': 36, 'C': 18}, 'Panel sizes differ')
    return result


def make_family(spec, used_scenes, used_families):
    rng = random.Random(ancestor.stable_seed(SEED, spec['label']))
    pair, trio, direction = spec['room_pair'], spec['trio'], spec['orientation']
    outside = [room for room in ROOMS if room not in pair]
    def background():
        return ('background', rng.choice(PEOPLE), rng.choice(outside))
    for attempt in range(10000):
        tokens = [('evidence', person, occurrence) for person in range(3) for occurrence in (0, 1)]
        tokens += [background() for _ in range(10)]
        rng.shuffle(tokens)
        flips = [rng.randrange(2) for _ in range(3)]
        layouts = [(16, tokens, None, [])]
        for low, high in ((16, 32), (32, 64)):
            tokens, positions = ancestor.interleave(rng, tokens, [background() for _ in range(high-low)])
            layouts.append((high, tokens, low, positions))
        rows = []
        for variant in range(3):
            others = [i for i in range(3) if i != variant]
            for n, layout, parent_n, positions in layouts:
                frames = []
                for kind, a, b in layout:
                    if kind == 'background':
                        frames.append([a, b])
                    else:
                        room = (b ^ flips[a]) if a == variant else (others.index(a) ^ direction)
                        frames.append([trio[a], pair[room]])
                states = ancestor.states_from_frames(frames)
                question = ancestor.global_prompt(pair)
                content = oid(dict(states=states, question=question))
                rows.append(dict(sid='ij_'+content[:24], split='fresh_'+spec['panel'], panel=spec['panel'],
                    contrast_id=spec['label'], pair_id=spec['label']+f'/v{variant}', variant=variant,
                    n_frames=n, k=6, room_pair=pair, trio=trio, orientation=direction,
                    original_training_orientation=spec['original_training_orientation'],
                    matches_training_orientation=spec['matches_training_orientation'],
                    question=question, local_prompt=question, gold=trio[variant], frames=frames,
                    states=states, content_sha256=content, parent_n_frames=parent_n,
                    parent_positions=positions, generation_attempt=attempt, seed=SEED))
        hashes = {row['content_sha256'] for row in rows}
        identities = {n: family_identity([r for r in rows if r['n_frames'] == n]) for n in LENGTHS}
        if len(hashes) == 9 and not hashes & used_scenes and not set(identities.values()) & used_families:
            for row in rows:
                row['family_instance_sha256'] = identities[row['n_frames']]
            used_scenes.update(hashes)
            used_families.update(identities.values())
            return rows
    raise ValueError('No fresh realization found for '+spec['label'])


def audit_family(rows):
    need(len(rows) == 9, 'Nine scenes per family required')
    by_n = defaultdict(list)
    for row in rows:
        by_n[row['n_frames']].append(row)
        pair, trio, frames = row['room_pair'], row['trio'], row['frames']
        need(row['seed'] == SEED and row['n_frames'] in LENGTHS and len(frames) == row['n_frames']
             and row['states'] == ancestor.states_from_frames(frames), 'Seed/length/canonical Step mismatch')
        need(len(trio) == len(set(trio)) == 3 and all(p in PEOPLE for p in trio)
             and tuple(pair) in ancestor.PAIRS and row['orientation'] in (0, 1), 'Invalid semantic support')
        need(all(p in PEOPLE and room in ROOMS for p, room in frames), 'Unknown frame semantics')
        relevant = [(i, p, room) for i, (p, room) in enumerate(frames) if room in pair]
        need(len(relevant) == row['k'] == 6
             and Counter(p for _, p, _ in relevant) == Counter({p: 2 for p in trio})
             and Counter(room for _, _, room in relevant) == Counter({room: 3 for room in pair}), 'Marginals differ')
        answers = [p for p in trio if {room for _, name, room in relevant if name == p} == set(pair)]
        need(answers == [row['gold']] and row['gold'] == trio[row['variant']], 'Unique join answer differs')
        others = [p for p in trio if p != row['gold']]
        for i, person in enumerate(others):
            need({room for _, p, room in relevant if p == person} == {pair[i ^ row['orientation']]}, 'Orientation differs')
        need(row['question'] == row['local_prompt'] == ancestor.global_prompt(pair)
             and oid(scene_content(row)) == row['content_sha256']
             and row['sid'] == 'ij_'+row['content_sha256'][:24], 'Prompt or content identity differs')
    need(set(by_n) == set(LENGTHS), 'All three lengths required')
    for n, group in by_n.items():
        group.sort(key=lambda row: row['variant'])
        need([r['variant'] for r in group] == [0, 1, 2], 'All answer-changing variants required')
        first = group[0]
        positions = [i for i, (_, room) in enumerate(first['frames']) if room in first['room_pair']]
        for row in group:
            for key in ('panel', 'split', 'contrast_id', 'trio', 'room_pair', 'orientation',
                        'original_training_orientation', 'matches_training_orientation', 'generation_attempt',
                        'parent_n_frames', 'parent_positions'):
                need(row[key] == first[key], 'Within-triple metadata differs: '+key)
            need([i for i, (_, room) in enumerate(row['frames']) if room in row['room_pair']] == positions
                 and [p for p, _ in row['frames']] == [p for p, _ in first['frames']]
                 and [f for i, f in enumerate(row['frames']) if i not in positions]
                     == [f for i, f in enumerate(first['frames']) if i not in positions], 'Variant layout/background differs')
            need(row['family_instance_sha256'] == family_identity(group), 'Concrete triple identity differs')
    for low, high in ((16, 32), (32, 64)):
        for parent, child in zip(by_n[low], by_n[high]):
            indices = child['parent_positions']
            need(child['parent_n_frames'] == low and len(indices) == low and indices == sorted(set(indices))
                 and all(0 <= i < high for i in indices), 'Invalid nested insertion map')
            need([child['frames'][i] for i in indices] == parent['frames']
                 and all(room not in child['room_pair'] for i, (_, room) in enumerate(child['frames']) if i not in set(indices))
                 and child['gold'] == parent['gold'] and child['pair_id'] == parent['pair_id'], 'Insertion changed evidence')
    need(all(r['parent_n_frames'] is None and r['parent_positions'] == [] for r in by_n[16]), 'Base has unexpected parent')


def generate(training_samples, excluded_scenes, excluded_families):
    used_scenes, used_families = set(excluded_scenes), set(excluded_families)
    rows = []
    for spec in panels(training_samples):
        rows.extend(make_family(spec, used_scenes, used_families))
    audit(rows, training_samples, excluded_scenes, excluded_families)
    return rows


def audit(rows, training_samples, excluded_scenes, excluded_families):
    specs = {spec['label']: spec for spec in panels(training_samples)}
    groups = defaultdict(list)
    for row in rows:
        groups[row['contrast_id']].append(row)
    need(len(rows) == 810 and set(groups) == set(specs), 'Panel/family cardinality differs')
    need(len({r['content_sha256'] for r in rows}) == len({r['sid'] for r in rows}) == 810
         and not {r['content_sha256'] for r in rows} & set(excluded_scenes), 'Scene freshness failed')
    need(len({r['family_instance_sha256'] for r in rows}) == 270
         and not {r['family_instance_sha256'] for r in rows} & set(excluded_families), 'Concrete family freshness failed')
    for label, group in groups.items():
        audit_family(group)
        for row in group:
            need(all(row[k] == specs[label][k] for k in specs[label] if k != 'label'), 'Panel cell differs from original support')
    for panel, count in (('A', 108), ('B', 108), ('C', 54)):
        for n in LENGTHS:
            cell = [r for r in rows if r['panel'] == panel and r['n_frames'] == n]
            need(len(cell) == count and Counter(r['gold'] for r in cell) == {p: count//9 for p in PEOPLE}, 'Cell/name balance differs')
            need(Counter(r['orientation'] for r in cell) == {0: count//2, 1: count//2}, 'Orientation balance differs')
            if panel == 'A':
                need(Counter(r['matches_training_orientation'] for r in cell) == {True: 54, False: 54}, 'Panel A orientation strata differ')
    need(sum(r['n_frames'] for r in rows) == 30240, 'Image occurrence inventory differs')
    return dict(passed=True,contexts=810,families=90,same_length_triples=270,image_occurrences=30240,
                all_nested_insertions_verified=True,all_concrete_family_and_scene_exclusions_verified=True,
                panel_A_original_and_opposite_orientation_contexts_per_length=54)


def self_test():
    # No call at import. The releasing stager must execute fixtures on Slurm CPU.
    spec = dict(panel='A', trio=list(PEOPLE[:3]), room_pair=['Kitchen','Office'], orientation=0,
                original_training_orientation=0, matches_training_orientation=True, label='fixture')
    first = make_family(spec, set(), set())
    audit_family(first)
    hashes = {r['content_sha256'] for r in first}; identities = {r['family_instance_sha256'] for r in first}
    second = make_family(spec, hashes.copy(), identities.copy())
    audit_family(second)
    need(second[0]['generation_attempt'] > first[0]['generation_attempt'], 'Collision rejection did not advance fixed RNG')
    triple = [r for r in first if r['n_frames'] == 16]
    changed_labels = [dict(r, sid='other', split='other', contrast_id='other', seed=0) for r in reversed(triple)]
    need(family_identity(triple) == family_identity(changed_labels), 'Concrete identity depends on labels or order')
    rejected = 0
    for mutate in (lambda r: r[0].update(gold=PEOPLE[-1]),
                   lambda r: r[1].update(parent_positions=list(reversed(r[1]['parent_positions']))),
                   lambda r: r[0]['states'][0].update(step_id=99),
                   lambda r: r[0].update(family_instance_sha256='0'*64)):
        bad = copy.deepcopy(first);mutate(bad)
        try:
            audit_family(bad)
        except (ValueError, IndexError):
            rejected += 1
        else:
            raise AssertionError('Invalid fresh family accepted')
    return dict(passed=True,corruptions_rejected=rejected,collision_rejection=True,metadata_independent_family_identity=True)
